#!/usr/bin/make -f
# DSP-only LV2 build of Electronic Echo 280 with the vendored DPF in ../../dpf
NAME = nhe-ec280
FILES_DSP = EC280Plugin.cpp
include ../../dpf/Makefile.plugins.mk
TARGETS = lv2_dsp
all: $(TARGETS)
